version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    ACCOUNT_ID: 461864990714
    BACKEND_REPO: 461864990714.dkr.ecr.ap-south-1.amazonaws.com/otr-ivr-backend
    FRONTEND_REPO: 461864990714.dkr.ecr.ap-south-1.amazonaws.com/otr-ivr-frontend

phases:
  pre_build:
    commands:
      - echo "Login to ECR"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 461864990714.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Getting commit tag"
      - TAG=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)
      - echo "Tag = $TAG"

  build:
    commands:
      - echo "Build Backend"
      - docker build -t backend:$TAG ./backend
      - docker tag backend:$TAG $BACKEND_REPO:$TAG
      - docker tag backend:$TAG $BACKEND_REPO:dev1

      - echo "Build Frontend"
      - docker build -t frontend:$TAG ./frontend
      - docker tag frontend:$TAG $FRONTEND_REPO:$TAG
      - docker tag frontend:$TAG $FRONTEND_REPO:dev1

  post_build:
    commands:
      - echo "Push Backend"
      - docker push $BACKEND_REPO:$TAG
      - docker push $BACKEND_REPO:dev1

      - echo "Push Frontend"
      - docker push $FRONTEND_REPO:$TAG
      - docker push $FRONTEND_REPO:dev1